In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
import os
from dotenv import load_dotenv
load_dotenv()

DATA_LOC = os.getenv("DATA_LOC")
print(DATA_LOC)

~/Data/DCIA_DATA/Data/

### RMBW Data

What is RMBW?
- Regionale Monitor Brede Welvaart
- Maps the braod prosperity of municipalities, provinces and COROP regions using 42 indicators
- broad prosperity concenrs the quality of life here and now and the extent to which this comes at the expense of that of future generations or of people elsewhere in the world

In [6]:
rmbw = pd.read_csv(DATA_LOC + "GENERAL SOURCES/rmbw2025_resultaten.csv")

print(rmbw.columns)
rmbw.head(50)

Index(['ind_code', 'statcode', 'trend_periode', 'trend_kleur', 'positie',
       'pos_van_n', 'pos_jaar', 'pos_kleur', 'een_na_laatste_jaar',
       'laatste_jaar', 'mut_tekst_nl', 'mut_kleur'],
      dtype='str')

,ind_code,statcode,trend_periode,trend_kleur,positie,pos_van_n,pos_jaar,pos_kleur,een_na_laatste_jaar,laatste_jaar,mut_tekst_nl,mut_kleur
0,01.07_NW,NL01,2017-2024,groen,1,1,2024,grijs,2023.0,2024.0,"-6,6%",rood
1,01.07_NW,PV22,2017-2024,groen,5,12,2024,grijs,2023.0,2024.0,"-3,8%",rood
2,01.07_NW,PV24,2017-2024,groen,6,12,2024,grijs,2023.0,2024.0,"-4,2%",rood
3,01.07_NW,PV21,2017-2024,groen,8,12,2024,grijs,2023.0,2024.0,"-4,4%",rood
4,01.07_NW,PV25,2017-2024,groen,3,12,2024,groen,2023.0,2024.0,"-4,1%",rood
5,01.07_NW,PV20,2017-2024,groen,12,12,2024,rood,2023.0,2024.0,"-9,4%",rood
6,01.07_NW,PV31,2017-2024,groen,9,12,2024,grijs,2023.0,2024.0,"-10,1%",rood
7,01.07_NW,PV30,2017-2024,groen,1,12,2024,groen,2023.0,2024.0,"-4,8%",rood
8,01.07_NW,PV27,2017-2024,groen,10,12,2024,rood,2023.0,2024.0,"-12,1%",rood
9,01.07_NW,PV23,2017-2024,groen,7,12,2024,grijs,2023.0,2024.0,"-2,4%",rood
10,01.07_NW,PV26,2017-2024,groen,2,12,2024,groen,2023.0,2024.0,"-12,0%",rood
11,01.07_NW,PV29,2017-2024,groen,4,12,2024,grijs,2023.0,2024.0,"+1,4%",groen
12,01.07_NW,PV28,2017-2024,groen,11,12,2024,rood,2023.0,2024.0,"-8,2%",rood
13,01.07_NW,CR14,2017-2024,groen,9,40,2024,groen,2023.0,2024.0,"-3,6%",rood
14,01.07_NW,CR26,2017-2024,groen,38,40,2024,rood,2023.0,2024.0,"-9,4%",rood
15,01.07_NW,CR21,2017-2024,groen,7,40,2024,groen,2023.0,2024.0,"-13,8%",rood
16,01.07_NW,CR25,2017-2024,groen,12,40,2024,grijs,2023.0,2024.0,"-11,1%",rood
17,01.07_NW,CR19,2017-2024,groen,2,40,2024,groen,2023.0,2024.0,"-3,0%",rood
18,01.07_NW,CR15,2017-2024,groen,34,40,2024,rood,2023.0,2024.0,"-7,5%",rood
19,01.07_NW,CR27,2017-2024,groen,35,40,2024,rood,2023.0,2024.0,"-17,3%",rood
20,01.07_NW,CR02,2017-2024,groen,33,40,2024,rood,2023.0,2024.0,"+4,2%",groen
21,01.07_NW,CR40,2017-2024,groen,24,40,2024,grijs,2023.0,2024.0,"-4,2%",rood
22,01.07_NW,CR23,2017-2024,groen,40,40,2024,rood,2023.0,2024.0,"-6,4%",rood
23,01.07_NW,CR29,2017-2024,groen,37,40,2024,rood,2023.0,2024.0,"-6,6%",rood
24,01.07_NW,CR24,2017-2024,groen,1,40,2024,groen,2023.0,2024.0,"-6,8%",rood
25,01.07_NW,CR20,2017-2024,groen,5,40,2024,groen,2023.0,2024.0,"-10,9%",rood
26,01.07_NW,CR18,2017-2024,groen,11,40,2024,grijs,2023.0,2024.0,"-3,1%",rood
27,01.07_NW,CR38,2017-2024,groen,13,40,2024,grijs,2023.0,2024.0,"-8,2%",rood
28,01.07_NW,CR34,2017-2024,groen,27,40,2024,grijs,2023.0,2024.0,"-4,2%",rood
29,01.07_NW,CR07,2017-2024,groen,10,40,2024,groen,2023.0,2024.0,"-3,6%",rood
30,01.07_NW,CR04,2017-2024,groen,31,40,2024,rood,2023.0,2024.0,"-3,2%",rood
31,01.07_NW,CR37,2017-2024,groen,22,40,2024,grijs,2023.0,2024.0,"-7,1%",rood
32,01.07_NW,CR10,2017-2024,groen,18,40,2024,grijs,2023.0,2024.0,"-1,9%",rood
33,01.07_NW,CR35,2017-2024,groen,4,40,2024,groen,2023.0,2024.0,"-4,4%",rood
34,01.07_NW,CR01,2017-2024,groen,32,40,2024,rood,2023.0,2024.0,"-1,4%",rood
35,01.07_NW,CR28,2017-2024,groen,8,40,2024,groen,2023.0,2024.0,"-4,1%",rood
36,01.07_NW,CR03,2017-2024,groen,39,40,2024,rood,2023.0,2024.0,"-17,5%",rood
37,01.07_NW,CR32,2017-2024,groen,21,40,2024,grijs,2023.0,2024.0,"+4,3%",groen
38,01.07_NW,CR12,2017-2024,groen,28,40,2024,grijs,2023.0,2024.0,"-3,2%",rood
39,01.07_NW,CR17,2017-2024,groen,16,40,2024,grijs,2023.0,2024.0,"-12,0%",rood
40,01.07_NW,CR13,2017-2024,groen,6,40,2024,groen,2023.0,2024.0,"-5,2%",rood
41,01.07_NW,CR33,2017-2024,groen,23,40,2024,grijs,2023.0,2024.0,"-5,9%",rood
42,01.07_NW,CR22,2017-2024,groen,29,40,2024,grijs,2023.0,2024.0,"-5,7%",rood
43,01.07_NW,CR31,2017-2024,groen,17,40,2024,grijs,2023.0,2024.0,"-4,3%",rood
44,01.07_NW,CR39,2017-2024,groen,36,40,2024,rood,2023.0,2024.0,"-13,0%",grijs
45,01.07_NW,CR08,2017-2024,groen,30,40,2024,grijs,2023.0,2024.0,"-3,8%",rood
46,01.07_NW,CR06,2017-2024,groen,25,40,2024,grijs,2023.0,2024.0,"-6,4%",rood
47,01.07_NW,CR36,2017-2024,groen,14,40,2024,grijs,2023.0,2024.0,"-4,7%",rood
48,01.07_NW,CR30,2017-2024,groen,26,40,2024,grijs,2023.0,2024.0,"-1,1%",rood
49,01.07_NW,CR09,2017-2024,groen,20,40,2024,grijs,2023.0,2024.0,"-3,1%",rood

In [9]:
print(rmbw.shape)

(12343, 12)

Columns
- ind_code: Looks like an indicator code
- statcode: city code or province code. From the translation city code would make sense, but looking at examples it seems to be region
- trend_periode: trend period
- 'trend_kleur: trend color
- 'positie': position
- 'pos_van_n': position out of n
- 'pos_jaar': position year
- 'pos_kleur: position colour
- 'een_na_laatste_jaar: one before last year (used to compute the change)
- 'laatste_jaar': last year
- 'mut_tekst_nl': mutation? text, looks like percentage change
- 'mut_kleur': mutation? color

In [7]:
print(rmbw["statcode"].unique())

<StringArray>
[  'NL01',   'PV22',   'PV24',   'PV21',   'PV25',   'PV20',   'PV31',
   'PV30',   'PV27',   'PV23',
 ...
 'GM0355', 'GM0299', 'GM0637', 'GM0638', 'GM1892', 'GM0879', 'GM0301',
 'GM1896', 'GM0642', 'GM0193']
Length: 395, dtype: str

Stat code is either province or city.  We should be able to get province codes and municipality codes from here: https://www.cbs.nl/nl-nl/onze-diensten/methoden/classificaties/overig/gemeentelijke-indelingen-per-jaar/indeling-per-jaar/gemeentelijke-indeling-op-1-januari-2026
- NL01 is probably the whole of the country
- PV is province
- GM is gementee, so municipality

In [8]:
print(rmbw["ind_code"].unique())

<StringArray>
[   '01.07_NW',    '01.10_NW',    '01_GZ_08',    '01_GZ_20',  '01_KL_H_01',
  '01_KL_H_36', '01_KL_OK_08', '01_KL_OK_10', '01_KL_OK_11', '01_KL_OK_14',
 '01_KL_OK_30', '01_KL_OK_39', '01_KL_PK_01', '01_KL_PK_03', '01_KL_PK_07',
 '02_HB_MK_30', '02_HB_NK_30', '02_HB_NK_31', '02_HB_SK_01',   '03_PVI_04',
    '04_VE_03',   '05_OPL_08',   '07_K&E_03',   '09_E&V_03',   '09_E&V_12',
   '09_E&V_13',    '10.31_NW',    '15.15_NW',   '18_FIN_32',     'R_GZ_03',
  'R_HN_AV_02', 'R_HN_MIL_01', 'R_HN_MIL_02',  'R_HN_SL_02',  'R_HN_SL_03',
  'R_HN_SL_04',   'R_HN_V_01',   'R_L_NK_01',   'R_L_NK_02',   'R_L_NK_03',
   'R_L_NK_04',   'R_L_SK_01']
Length: 42, dtype: str

IND code stands for the indicator code. We have 42 separate indicators.

- description of the indicators: https://www.cbs.nl/nl-nl/visualisaties/regionale-monitor-brede-welvaart/beschrijving-indicatoren
- These 42 indicators seem crucial and very useful, from distance to green areas to OV, to cofees, green house gases, GDP. We should be able to build a ton of indicators around this data.

In [17]:
print(rmbw["trend_periode"].unique())

#Only have one period, 2017-2024

<StringArray>
['2017-2024']
Length: 1, dtype: str

This has only position from N no actual indicator values. What is the position compared with, the region?

In [38]:
rmbw["percentile"] = rmbw["positie"] / rmbw["pos_van_n"]

rmbw.head()

,ind_code,statcode,trend_periode,trend_kleur,positie,pos_van_n,pos_jaar,pos_kleur,een_na_laatste_jaar,laatste_jaar,mut_tekst_nl,mut_kleur,percentile
0,01.07_NW,NL01,2017-2024,groen,1,1,2024,grijs,2023.0,2024.0,"-6,6%",rood,1.000000
1,01.07_NW,PV22,2017-2024,groen,5,12,2024,grijs,2023.0,2024.0,"-3,8%",rood,0.416667
2,01.07_NW,PV24,2017-2024,groen,6,12,2024,grijs,2023.0,2024.0,"-4,2%",rood,0.500000
3,01.07_NW,PV21,2017-2024,groen,8,12,2024,grijs,2023.0,2024.0,"-4,4%",rood,0.666667
4,01.07_NW,PV25,2017-2024,groen,3,12,2024,groen,2023.0,2024.0,"-4,1%",rood,0.250000

Pivot table of municipality/province in the top percentile for each category

In [39]:
rmbw_pivot = rmbw.pivot_table(
    index="statcode",
    columns=["ind_code"],
    values="percentile",
    aggfunc="first" #This will only give one value so no need for calculating mean or any other agg func, I checked
)

rmbw_pivot.head(50)

ind_code,01.07_NW,01.10_NW,01_GZ_08,01_GZ_20,01_KL_H_01,01_KL_H_36,01_KL_OK_08,01_KL_OK_10,01_KL_OK_11,01_KL_OK_14,...,R_HN_MIL_02,R_HN_SL_02,R_HN_SL_03,R_HN_SL_04,R_HN_V_01,R_L_NK_01,R_L_NK_02,R_L_NK_03,R_L_NK_04,R_L_SK_01
statcode,,,,,,,,,,,,,,,,,,,,,
CR01,0.800000,0.875000,1.000000,NaN,0.325000,0.975000,0.625000,0.900000,1.000000,0.900000,...,0.375000,0.325000,0.850000,0.850000,NaN,NaN,NaN,0.225000,0.200000,NaN
CR02,0.825000,0.850000,0.950000,NaN,0.100000,0.950000,0.075000,0.750000,0.975000,1.000000,...,0.825000,0.325000,1.000000,0.650000,NaN,NaN,NaN,0.200000,0.225000,NaN
CR03,0.975000,0.350000,0.100000,NaN,0.950000,1.000000,0.875000,0.450000,0.525000,0.875000,...,0.550000,0.650000,0.650000,0.475000,NaN,NaN,NaN,0.325000,0.625000,NaN
CR04,0.775000,0.575000,0.575000,NaN,0.375000,0.900000,0.650000,0.150000,0.450000,0.350000,...,0.125000,0.125000,0.350000,0.625000,NaN,NaN,NaN,0.100000,0.450000,NaN
CR05,0.375000,0.100000,0.450000,NaN,0.075000,0.725000,0.225000,0.125000,0.375000,0.950000,...,0.325000,0.325000,0.850000,0.725000,NaN,NaN,NaN,0.025000,0.350000,NaN
CR06,0.625000,0.450000,0.500000,NaN,0.300000,0.800000,0.900000,0.200000,0.700000,0.550000,...,0.150000,0.325000,0.650000,0.725000,NaN,NaN,NaN,0.175000,0.175000,NaN
CR07,0.250000,0.050000,0.650000,NaN,0.350000,0.250000,0.925000,0.325000,0.325000,0.150000,...,0.025000,0.650000,0.850000,0.875000,NaN,NaN,NaN,0.050000,0.075000,NaN
CR08,0.750000,0.775000,0.975000,NaN,0.150000,0.875000,0.675000,0.375000,0.950000,0.575000,...,0.100000,0.950000,0.850000,0.975000,NaN,NaN,NaN,0.250000,0.050000,NaN
CR09,0.500000,0.175000,0.725000,NaN,0.250000,0.625000,0.800000,0.025000,0.725000,0.175000,...,0.050000,0.650000,0.850000,1.000000,NaN,NaN,NaN,0.125000,0.250000,NaN
CR10,0.450000,0.100000,0.325000,NaN,0.050000,0.450000,0.475000,0.050000,0.250000,0.450000,...,0.250000,0.650000,0.650000,0.725000,NaN,NaN,NaN,0.275000,0.375000,NaN
CR11,0.475000,0.550000,0.350000,NaN,0.200000,0.500000,0.375000,0.300000,0.200000,0.650000,...,0.500000,0.650000,0.650000,0.875000,NaN,NaN,NaN,0.375000,0.550000,NaN
CR12,0.700000,0.725000,0.550000,NaN,0.225000,0.750000,0.100000,0.425000,0.300000,0.325000,...,0.400000,0.125000,0.350000,0.475000,NaN,NaN,NaN,0.450000,0.425000,NaN
CR13,0.150000,0.100000,0.275000,NaN,0.425000,0.300000,0.725000,0.175000,0.400000,0.050000,...,0.075000,0.650000,0.350000,0.525000,NaN,NaN,NaN,0.425000,0.475000,NaN
CR14,0.225000,0.050000,0.750000,NaN,0.550000,0.400000,0.525000,0.075000,0.425000,0.625000,...,0.275000,0.650000,0.650000,0.600000,NaN,NaN,NaN,0.350000,0.150000,NaN
CR15,0.850000,0.650000,0.250000,NaN,0.900000,0.800000,0.600000,0.625000,0.100000,0.250000,...,0.575000,0.325000,0.350000,0.300000,NaN,NaN,NaN,0.700000,0.725000,NaN
CR16,0.075000,0.500000,0.900000,NaN,0.525000,0.175000,0.975000,0.250000,0.800000,0.800000,...,0.600000,0.650000,0.650000,0.675000,NaN,NaN,NaN,0.500000,0.100000,NaN
CR17,0.400000,0.350000,0.075000,NaN,0.675000,0.100000,0.400000,0.475000,0.025000,0.375000,...,0.750000,0.325000,0.100000,0.525000,NaN,NaN,NaN,0.675000,0.750000,NaN
CR18,0.275000,0.400000,0.625000,NaN,0.125000,0.400000,0.300000,0.650000,0.750000,0.850000,...,0.625000,0.125000,0.350000,0.675000,NaN,NaN,NaN,0.400000,0.500000,NaN
CR19,0.050000,0.275000,0.200000,NaN,0.175000,0.150000,0.250000,0.775000,0.500000,0.300000,...,0.700000,0.650000,0.100000,0.375000,NaN,NaN,NaN,0.725000,0.575000,NaN
CR20,0.125000,0.650000,0.400000,NaN,0.875000,0.125000,0.275000,0.675000,0.675000,0.100000,...,0.650000,0.025000,0.025000,0.075000,NaN,NaN,NaN,0.825000,0.775000,NaN
CR21,0.175000,0.625000,0.025000,NaN,0.925000,0.050000,0.050000,0.875000,0.125000,0.025000,...,0.725000,0.025000,0.025000,0.075000,NaN,NaN,NaN,0.875000,0.950000,NaN
CR22,0.725000,0.925000,0.600000,NaN,0.725000,0.550000,0.025000,0.850000,0.625000,0.525000,...,0.850000,0.325000,0.350000,0.375000,NaN,NaN,NaN,0.800000,0.900000,NaN
CR23,1.000000,0.900000,0.050000,NaN,0.975000,0.675000,0.700000,0.975000,0.150000,0.925000,...,0.975000,0.650000,0.100000,0.275000,NaN,NaN,NaN,0.950000,1.000000,NaN
CR24,0.025000,0.650000,0.125000,NaN,0.700000,0.025000,0.150000,0.725000,0.075000,0.075000,...,0.675000,0.950000,0.100000,0.725000,NaN,NaN,NaN,0.900000,0.875000,NaN
CR25,0.300000,0.025000,0.175000,NaN,0.500000,0.225000,0.200000,0.350000,0.050000,0.675000,...,0.925000,0.025000,0.100000,0.375000,NaN,NaN,NaN,0.925000,0.850000,NaN
CR26,0.950000,1.000000,0.225000,NaN,0.800000,0.700000,0.125000,0.925000,0.225000,0.400000,...,0.950000,0.125000,0.025000,0.150000,NaN,NaN,NaN,0.975000,0.975000,NaN
CR27,0.875000,0.175000,0.150000,NaN,0.275000,0.800000,0.425000,0.100000,0.275000,0.975000,...,1.000000,0.650000,0.100000,0.175000,NaN,NaN,NaN,1.000000,0.800000,NaN
CR28,0.200000,0.525000,0.425000,NaN,0.025000,0.075000,0.575000,0.225000,0.175000,0.725000,...,0.800000,0.325000,0.350000,0.375000,NaN,NaN,NaN,0.575000,0.650000,NaN
CR29,0.925000,0.975000,0.775000,NaN,0.775000,0.750000,0.550000,0.950000,0.600000,0.775000,...,0.900000,0.125000,0.100000,0.300000,NaN,NaN,NaN,0.850000,0.925000,NaN
CR30,0.650000,0.825000,0.800000,NaN,0.400000,0.350000,0.175000,0.500000,0.550000,0.825000,...,0.875000,0.650000,0.100000,0.525000,NaN,NaN,NaN,0.750000,0.825000,NaN
CR31,0.425000,0.400000,0.850000,NaN,0.575000,0.625000,1.000000,0.575000,0.900000,0.700000,...,0.175000,0.325000,0.850000,0.725000,NaN,NaN,NaN,0.075000,0.325000,NaN
CR32,0.525000,0.175000,0.375000,NaN,0.450000,0.525000,0.500000,0.550000,0.575000,0.750000,...,0.425000,0.325000,0.350000,0.925000,NaN,NaN,NaN,0.300000,0.300000,NaN
CR33,0.575000,0.725000,0.675000,NaN,0.600000,0.375000,0.325000,0.700000,0.775000,0.500000,...,0.525000,0.325000,0.350000,0.175000,NaN,NaN,NaN,0.650000,0.700000,NaN
CR34,0.675000,0.600000,0.700000,NaN,0.625000,0.575000,0.825000,0.600000,0.475000,0.275000,...,0.450000,0.125000,0.100000,0.175000,NaN,NaN,NaN,0.525000,0.600000,NaN
CR35,0.100000,0.250000,0.475000,NaN,0.650000,0.200000,0.450000,0.275000,0.350000,0.425000,...,0.475000,0.325000,0.350000,0.300000,NaN,NaN,NaN,0.600000,0.275000,NaN
CR36,0.350000,0.275000,0.300000,NaN,0.825000,0.275000,0.750000,0.525000,0.650000,0.125000,...,0.350000,0.125000,0.100000,0.175000,NaN,NaN,NaN,0.625000,0.400000,NaN
CR37,0.550000,0.275000,0.825000,NaN,1.000000,0.600000,0.775000,0.400000,0.850000,0.200000,...,0.200000,0.325000,0.350000,0.075000,NaN,NaN,NaN,0.550000,0.025000,NaN
CR38,0.325000,0.450000,0.525000,NaN,0.475000,0.475000,0.850000,0.800000,0.925000,0.225000,...,0.225000,0.125000,0.650000,0.050000,NaN,NaN,NaN,0.475000,0.125000,NaN
CR39,0.900000,0.800000,0.875000,NaN,0.750000,0.925000,0.350000,1.000000,0.875000,0.600000,...,0.775000,0.025000,0.350000,0.025000,NaN,NaN,NaN,0.775000,0.675000,NaN
CR40,0.600000,0.950000,0.925000,NaN,0.850000,0.300000,0.950000,0.825000,0.825000,0.475000,...,0.300000,0.950000,0.650000,0.950000,NaN,NaN,NaN,0.150000,0.525000,NaN
GM0014,0.997076,0.523392,0.014706,0.845029,0.991111,0.997050,0.923077,0.683544,0.232456,0.652047,...,0.780702,0.461988,0.380117,0.251462,0.909091,NaN,NaN,0.690058,0.921053,0.690909
GM0034,0.766082,0.988304,0.929412,0.567251,0.946667,0.457227,0.965812,0.962025,0.850877,0.280702,...,0.675439,0.903509,0.014620,0.868421,0.400000,NaN,NaN,0.771930,0.804094,0.854545
GM0037,0.874269,0.842105,0.985294,0.991228,0.506667,0.964602,0.623932,0.814346,0.991228,0.704678,...,0.470760,0.102339,0.824561,0.780702,NaN,NaN,NaN,0.365497,0.394737,NaN
GM0047,0.909357,0.921053,0.994118,0.874269,1.080000,0.917404,0.572650,0.607595,0.978070,0.979532,...,0.903509,0.254386,0.380117,0.342105,NaN,NaN,NaN,0.523392,0.336257,NaN
GM0050,0.549708,0.646199,0.597059,0.038012,NaN,0.303835,NaN,NaN,NaN,0.307018,...,0.040936,0.935673,0.988304,0.833333,NaN,NaN,NaN,0.017544,0.292398,NaN
GM0059,0.763158,0.602339,0.950000,0.678363,NaN,0.929204,1.004274,1.004219,1.004386,0.678363,...,0.459064,0.020468,0.119883,0.751462,NaN,NaN,NaN,0.394737,0.453216,NaN
GM0060,0.301170,0.254386,0.917647,0.289474,NaN,0.929204,NaN,NaN,NaN,0.040936,...,0.014620,0.020468,0.380117,0.342105,NaN,NaN,NaN,0.014620,0.558480,NaN
GM0072,0.906433,0.769006,0.826471,0.897661,NaN,0.958702,NaN,NaN,NaN,0.932749,...,0.853801,0.102339,0.119883,0.593567,NaN,NaN,NaN,0.663743,0.517544,NaN
GM0074,0.777778,0.634503,0.194118,0.608187,0.382222,0.840708,0.867521,0.421941,0.289474,0.581871,...,0.406433,0.464912,0.824561,0.853801,NaN,NaN,NaN,0.330409,0.593567,NaN
GM0080,0.941520,0.883041,0.205882,0.769006,0.777778,0.967552,0.739316,0.379747,0.153509,0.736842,...,0.657895,0.251462,0.380117,0.529240,0.763636,NaN,NaN,0.423977,0.818713,0.145455